### PR TITLE
feat: Provide Docker option for setting up backend

### PR DESCRIPTION
**Pull request by tristanoneil**
🐳✨🐳✨🐳✨🐳✨🐳✨ 🐳✨ 🐳✨ 🐳✨ 🐳✨ 🐳✨ 🐳✨ 🐳✨ 🐳✨ 🐳

Many of the reported issues are caused by minor discrepancies across developers computers. Providing a Docker option should be more full proof in that we're starting with a known quantity (the base image). The commit message has a bit more detail explaining what's changed and why.

### CODE REVIEW

**Comment by prichey** [comment]
When running through the installation process with docker, I don't get the standard prompts to 1) replace my WP installation and 2) to create a new DB. Were these changes intentional?

**Comment by tristanoneil** [comment]
@prichey It was intentional as I was initially not running the installer with `tty` but now I am ... I think I'll bring them back.

**Comment by tristanoneil** [comment]
@prichey it'll ask now 😄

**Comment by tristanoneil** [comment]
No need to run `postinstall`, `yarn docker:start` runs `./start_docker.sh` which runs `robo wordpress:setup` and assuming that works starts `wp server`.

**Comment by prichey** [comment]
Interesting, it looks like Docker cached the result of running that script. (Terminal output [here](https://gist.github.com/prichey/44bdd45e8811963eb3961d426740dba3)).

Wonder if it's worth throwing a `--no-cache` on the `docker build` step?

**Comment by prichey** [comment]
Huh, even with `--no-cache` I'm still not getting the prompt. Does it work for you locally?

https://gist.github.com/prichey/e8f283000967dfd95944f363066c8159

**Comment by tristanoneil** [comment]
@prichey made one tiny little change and it all broke 😄. Apparently `CMD` doesn't like single quotes, who knew. Should work in bbef810.

**Comment by prichey** [comment]
Works! LGTM

**Comment by ginatrapani** [comment]
This is fantastic, thank you so much @tristanoneil!

**Pull request merged**
